import React, { useState, useMemo } from 'react';
import { DashboardLayout } from '../components/DashboardLayout';
import { 
  Activity, 
  Download, 
  Sparkles, 
  CreditCard, 
  Settings, 
  ArrowRight,
  Filter,
  CheckCircle2,
  Trash2
} from 'lucide-react';

interface ActivityLog {
  id: string;
  type: 'download' | 'validation' | 'billing' | 'security';
  title: string;
  description: string;
  time: string;
  date: string;
  status: 'success' | 'warning' | 'info';
  metadata?: string;
}

const INITIAL_ACTIVITIES: ActivityLog[] = [
  {
    id: 'act-1',
    type: 'download',
    title: 'SaaS Builder Skill Downloaded',
    description: 'Downloaded file saas-builder-v1.2-SKILL.md (Size: 12KB)',
    time: '04:12 PM',
    date: 'Jun 03, 2026',
    status: 'success',
    metadata: 'Version v1.2'
  },
  {
    id: 'act-2',
    type: 'validation',
    title: 'AI Validation Audit Executed',
    description: 'Validated startup canvas report for MedConnect AI with final viability score 87%',
    time: '11:20 AM',
    date: 'Jun 02, 2026',
    status: 'success',
    metadata: 'Report ID: rep-medconnect'
  },
  {
    id: 'act-3',
    type: 'download',
    title: 'README Setup Guide Opened',
    description: 'Viewed instructions readme for SEO Optimizer Skill inside the dashboard drawer',
    time: '09:05 AM',
    date: 'Jun 01, 2026',
    status: 'info'
  },
  {
    id: 'act-4',
    type: 'billing',
    title: 'Stripe Payment Sandbox Completed',
    description: 'Purchased Builder Bundle Plan ($29.00). Invoicing receipts generated by Stripe.',
    time: '03:45 PM',
    date: 'May 25, 2026',
    status: 'success',
    metadata: 'Tx ID: ch_3Tasv5RFXAQMEApB12BNaVLf'
  },
  {
    id: 'act-5',
    type: 'security',
    title: 'Security Password Updated',
    description: 'Founder workspace access password was updated securely.',
    time: '10:14 AM',
    date: 'May 25, 2026',
    status: 'warning'
  },
  {
    id: 'act-6',
    type: 'validation',
    title: 'AI Validation Audit Executed',
    description: 'Validated startup canvas report for FinFlow Audit with final viability score 76%',
    time: '02:30 PM',
    date: 'May 20, 2026',
    status: 'success',
    metadata: 'Report ID: rep-finflow'
  }
];

export function DashboardActivity() {
  const [activities, setActivities] = useState<ActivityLog[]>(INITIAL_ACTIVITIES);
  const [filterType, setFilterType] = useState<'all' | 'download' | 'validation' | 'billing' | 'security'>('all');

  const filteredActivities = useMemo(() => {
    if (filterType === 'all') return activities;
    return activities.filter(a => a.type === filterType);
  }, [activities, filterType]);

  const getActivityIcon = (type: ActivityLog['type']) => {
    switch (type) {
      case 'download': return <Download size={14} className="text-emerald-600" />;
      case 'validation': return <Sparkles size={14} className="text-[#8B5CF6]" />;
      case 'billing': return <CreditCard size={14} className="text-blue-600" />;
      case 'security': return <Settings size={14} className="text-amber-600" />;
      default: return <Activity size={14} className="text-slate-600" />;
    }
  };

  const getStatusColor = (status: ActivityLog['status']) => {
    switch (status) {
      case 'success': return 'bg-emerald-50 border-emerald-100 text-emerald-600';
      case 'warning': return 'bg-amber-50 border-amber-200 text-amber-600';
      case 'info': return 'bg-blue-50 border-blue-100 text-blue-600';
      default: return 'bg-slate-50 border-slate-200 text-slate-500';
    }
  };

  const handleClearLog = () => {
    if (confirm('Are you sure you want to clear your activity log?')) {
      setActivities([]);
    }
  };

  return (
    <DashboardLayout>
      <main className="flex-1 p-6 md:p-10 max-w-[1200px] w-full mx-auto bg-[#FAF9F6] min-h-screen text-left">
        
        {/* Page Header */}
        <div className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-extrabold text-slate-900 mb-1.5 tracking-tight">Activity Log</h1>
            <p className="text-slate-550 text-sm font-medium">Audit trail of all actions, skill downloads, and billing logs</p>
          </div>
          {activities.length > 0 && (
            <button 
              onClick={handleClearLog}
              className="bg-white border border-slate-250 hover:bg-slate-50 text-slate-700 font-semibold px-4 py-2.5 rounded-xl text-xs flex items-center gap-2 transition-colors shadow-sm"
            >
              <Trash2 size={14} /> Clear Log
            </button>
          )}
        </div>

        {/* Filter Toolbar */}
        <div className="bg-white border border-slate-200/70 rounded-2xl p-1 shadow-sm flex overflow-x-auto w-full max-w-lg mb-8">
          {[
            { label: 'All Activity', type: 'all' },
            { label: 'Downloads', type: 'download' },
            { label: 'Audits', type: 'validation' },
            { label: 'Payments', type: 'billing' },
            { label: 'Settings', type: 'security' },
          ].map(btn => (
            <button
              key={btn.type}
              onClick={() => setFilterType(btn.type as any)}
              className={`px-4 py-2 rounded-xl text-xs font-bold transition-all flex-shrink-0 flex items-center gap-1.5 ${
                filterType === btn.type
                  ? 'bg-[#8B5CF6] text-white shadow-sm'
                  : 'text-slate-500 hover:text-slate-800'
              }`}
            >
              {btn.label}
            </button>
          ))}
        </div>

        {/* Timeline Log */}
        {filteredActivities.length === 0 ? (
          <div className="bg-white border border-slate-200 rounded-3xl p-16 text-center space-y-4 shadow-sm">
            <div className="w-16 h-16 bg-[#8B5CF6]/5 border border-[#8B5CF6]/10 text-[#8B5CF6] rounded-2xl flex items-center justify-center mx-auto">
              <Activity size={28} className="text-[#8B5CF6]" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-slate-900">Log is empty</h3>
              <p className="text-slate-500 text-sm">No activity logs recorded under this filter.</p>
            </div>
          </div>
        ) : (
          <div className="bg-white border border-slate-200/70 rounded-3xl p-6 md:p-8 shadow-sm relative overflow-hidden">
            
            {/* Vertical timeline connector line */}
            <div className="absolute top-10 bottom-10 left-12 w-0.5 bg-slate-100 hidden md:block" />

            <div className="space-y-8 relative">
              {filteredActivities.map((act) => (
                <div key={act.id} className="flex flex-col md:flex-row gap-4 md:gap-8 items-start">
                  
                  {/* Timeline Badge Date (Desktop) */}
                  <div className="w-24 text-right hidden md:block shrink-0 pt-1.5">
                    <span className="block text-[10px] text-slate-450 font-bold uppercase tracking-wider">{act.date}</span>
                    <span className="block text-[9px] text-slate-400 font-bold mt-0.5">{act.time}</span>
                  </div>

                  {/* Timeline Node Icon */}
                  <div className="w-9 h-9 rounded-xl bg-slate-50 border border-slate-200 flex items-center justify-center shrink-0 relative z-10 shadow-sm">
                    {getActivityIcon(act.type)}
                  </div>

                  {/* Content Card */}
                  <div className="flex-1 bg-white border border-slate-100 rounded-2xl p-4 md:p-5 text-left flex flex-col sm:flex-row justify-between sm:items-center gap-4 hover:border-slate-200 hover:shadow-sm transition-all duration-200">
                    <div>
                      {/* Mobile Date/Time info */}
                      <div className="flex items-center gap-2 mb-1.5 md:hidden">
                        <span className="text-[10px] text-[#8B5CF6] font-bold uppercase tracking-wider">{act.date}</span>
                        <span className="text-[10px] text-slate-400 font-bold">•</span>
                        <span className="text-[10px] text-slate-450 font-bold">{act.time}</span>
                      </div>
                      
                      <h4 className="text-sm font-bold text-slate-900 leading-tight mb-1">{act.title}</h4>
                      <p className="text-slate-500 text-xs font-medium leading-relaxed">{act.description}</p>
                    </div>

                    {/* Status Pill */}
                    <div className="flex items-center gap-2 shrink-0">
                      {act.metadata && (
                        <span className="text-[9px] font-bold text-slate-450 border border-slate-200 px-2 py-0.5 rounded uppercase">
                          {act.metadata}
                        </span>
                      )}
                      <span className={`text-[8px] font-bold px-2 py-0.5 rounded-full border uppercase tracking-wider ${getStatusColor(act.status)}`}>
                        {act.status}
                      </span>
                    </div>
                  </div>

                </div>
              ))}
            </div>

          </div>
        )}

      </main>
    </DashboardLayout>
  );
}
